[ { type: 'heading', depth: 1, text: 'Markdown: Syntax' },
  { type: 'html',
    pre: false,
    text: '<ul id="ProjectSubmenu">\n    <li><a href="/projects/markdown/" title="Markdown Project Page">Main</a></li>\n    <li><a href="/projects/markdown/basics" title="Markdown Basics">Basics</a></li>\n    <li><a class="selected" title="Markdown Syntax Documentation">Syntax</a></li>\n    <li><a href="/projects/markdown/license" title="Pricing and License Information">License</a></li>\n    <li><a href="/projects/markdown/dingus" title="Online Markdown Web Form">Dingus</a></li>\n</ul>\n\n\n' },
  { type: 'list_start', ordered: false },
  { type: 'list_item_start' },
  { type: 'text', text: '[Overview](#overview)' },
  { type: 'list_start', ordered: false },
  { type: 'list_item_start' },
  { type: 'text', text: '[Philosophy](#philosophy)' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Inline HTML](#html)' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text',
    text: '[Automatic Escaping for Special Characters](#autoescape)' },
  { type: 'list_item_end' },
  { type: 'list_end' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Block Elements](#block)' },
  { type: 'list_start', ordered: false },
  { type: 'list_item_start' },
  { type: 'text', text: '[Paragraphs and Line Breaks](#p)' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Headers](#header)' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Blockquotes](#blockquote)' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Lists](#list)' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Code Blocks](#precode)' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Horizontal Rules](#hr)' },
  { type: 'list_item_end' },
  { type: 'list_end' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Span Elements](#span)' },
  { type: 'list_start', ordered: false },
  { type: 'list_item_start' },
  { type: 'text', text: '[Links](#link)' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Emphasis](#em)' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Code](#code)' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Images](#img)' },
  { type: 'list_item_end' },
  { type: 'list_end' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Miscellaneous](#misc)' },
  { type: 'list_start', ordered: false },
  { type: 'list_item_start' },
  { type: 'text', text: '[Backslash Escapes](#backslash)' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: '[Automatic Links](#autolink)' },
  { type: 'space' },
  { type: 'list_item_end' },
  { type: 'list_end' },
  { type: 'list_item_end' },
  { type: 'list_end' },
  { type: 'paragraph',
    text: '**Note:** This document is itself written using Markdown; you\ncan [see the source for it by adding \'.text\' to the URL][src].' },
  { type: 'hr' },
  { type: 'html',
    pre: false,
    text: '<h2 id="overview">Overview</h2>\n\n' },
  { type: 'html',
    pre: false,
    text: '<h3 id="philosophy">Philosophy</h3>\n\n' },
  { type: 'paragraph',
    text: 'Markdown is intended to be as easy-to-read and easy-to-write as is feasible.' },
  { type: 'paragraph',
    text: 'Readability, however, is emphasized above all else. A Markdown-formatted\ndocument should be publishable as-is, as plain text, without looking\nlike it\'s been marked up with tags or formatting instructions. While\nMarkdown\'s syntax has been influenced by several existing text-to-HTML\nfilters -- including [Setext] [1], [atx] [2], [Textile] [3], [reStructuredText] [4],\n[Grutatext] [5], and [EtText] [6] -- the single biggest source of\ninspiration for Markdown\'s syntax is the format of plain text email.' },
  { type: 'paragraph',
    text: 'To this end, Markdown\'s syntax is comprised entirely of punctuation\ncharacters, which punctuation characters have been carefully chosen so\nas to look like what they mean. E.g., asterisks around a word actually\nlook like \\*emphasis\\*. Markdown lists look like, well, lists. Even\nblockquotes look like quoted passages of text, assuming you\'ve ever\nused email.' },
  { type: 'html',
    pre: false,
    text: '<h3 id="html">Inline HTML</h3>\n\n' },
  { type: 'paragraph',
    text: 'Markdown\'s syntax is intended for one purpose: to be used as a\nformat for *writing* for the web.' },
  { type: 'paragraph',
    text: 'Markdown is not a replacement for HTML, or even close to it. Its\nsyntax is very small, corresponding only to a very small subset of\nHTML tags. The idea is *not* to create a syntax that makes it easier\nto insert HTML tags. In my opinion, HTML tags are already easy to\ninsert. The idea for Markdown is to make it easy to read, write, and\nedit prose. HTML is a *publishing* format; Markdown is a *writing*\nformat. Thus, Markdown\'s formatting syntax only addresses issues that\ncan be conveyed in plain text.' },
  { type: 'paragraph',
    text: 'For any markup that is not covered by Markdown\'s syntax, you simply\nuse HTML itself. There\'s no need to preface it or delimit it to\nindicate that you\'re switching from Markdown to HTML; you just use\nthe tags.' },
  { type: 'paragraph',
    text: 'The only restrictions are that block-level HTML elements -- e.g. `<div>`,\n`<table>`, `<pre>`, `<p>`, etc. -- must be separated from surrounding\ncontent by blank lines, and the start and end tags of the block should\nnot be indented with tabs or spaces. Markdown is smart enough not\nto add extra (unwanted) `<p>` tags around HTML block-level tags.' },
  { type: 'paragraph',
    text: 'For example, to add an HTML table to a Markdown article:' },
  { type: 'code',
    text: 'This is a regular paragraph.\n\n<table>\n    <tr>\n        <td>Foo</td>\n    </tr>\n</table>\n\nThis is another regular paragraph.' },
  { type: 'paragraph',
    text: 'Note that Markdown formatting syntax is not processed within block-level\nHTML tags. E.g., you can\'t use Markdown-style `*emphasis*` inside an\nHTML block.' },
  { type: 'paragraph',
    text: 'Span-level HTML tags -- e.g. `<span>`, `<cite>`, or `<del>` -- can be\nused anywhere in a Markdown paragraph, list item, or header. If you\nwant, you can even use HTML tags instead of Markdown formatting; e.g. if\nyou\'d prefer to use HTML `<a>` or `<img>` tags instead of Markdown\'s\nlink or image syntax, go right ahead.' },
  { type: 'paragraph',
    text: 'Unlike block-level HTML tags, Markdown syntax *is* processed within\nspan-level tags.' },
  { type: 'html',
    pre: false,
    text: '<h3 id="autoescape">Automatic Escaping for Special Characters</h3>\n\n' },
  { type: 'paragraph',
    text: 'In HTML, there are two characters that demand special treatment: `<`\nand `&`. Left angle brackets are used to start tags; ampersands are\nused to denote HTML entities. If you want to use them as literal\ncharacters, you must escape them as entities, e.g. `&lt;`, and\n`&amp;`.' },
  { type: 'paragraph',
    text: 'Ampersands in particular are bedeviling for web writers. If you want to\nwrite about \'AT&T\', you need to write \'`AT&amp;T`\'. You even need to\nescape ampersands within URLs. Thus, if you want to link to:' },
  { type: 'code',
    text: 'http://images.google.com/images?num=30&q=larry+bird' },
  { type: 'paragraph', text: 'you need to encode the URL as:' },
  { type: 'code',
    text: 'http://images.google.com/images?num=30&amp;q=larry+bird' },
  { type: 'paragraph',
    text: 'in your anchor tag `href` attribute. Needless to say, this is easy to\nforget, and is probably the single most common source of HTML validation\nerrors in otherwise well-marked-up web sites.' },
  { type: 'paragraph',
    text: 'Markdown allows you to use these characters naturally, taking care of\nall the necessary escaping for you. If you use an ampersand as part of\nan HTML entity, it remains unchanged; otherwise it will be translated\ninto `&amp;`.' },
  { type: 'paragraph',
    text: 'So, if you want to include a copyright symbol in your article, you can write:' },
  { type: 'code', text: '&copy;' },
  { type: 'paragraph',
    text: 'and Markdown will leave it alone. But if you write:' },
  { type: 'code', text: 'AT&T' },
  { type: 'paragraph', text: 'Markdown will translate it to:' },
  { type: 'code', text: 'AT&amp;T' },
  { type: 'paragraph',
    text: 'Similarly, because Markdown supports [inline HTML](#html), if you use\nangle brackets as delimiters for HTML tags, Markdown will treat them as\nsuch. But if you write:' },
  { type: 'code', text: '4 < 5' },
  { type: 'paragraph', text: 'Markdown will translate it to:' },
  { type: 'code', text: '4 &lt; 5' },
  { type: 'paragraph',
    text: 'However, inside Markdown code spans and blocks, angle brackets and\nampersands are *always* encoded automatically. This makes it easy to use\nMarkdown to write about HTML code. (As opposed to raw HTML, which is a\nterrible format for writing about HTML syntax, because every single `<`\nand `&` in your example code needs to be escaped.)' },
  { type: 'hr' },
  { type: 'html',
    pre: false,
    text: '<h2 id="block">Block Elements</h2>\n\n\n' },
  { type: 'html',
    pre: false,
    text: '<h3 id="p">Paragraphs and Line Breaks</h3>\n\n' },
  { type: 'paragraph',
    text: 'A paragraph is simply one or more consecutive lines of text, separated\nby one or more blank lines. (A blank line is any line that looks like a\nblank line -- a line containing nothing but spaces or tabs is considered\nblank.) Normal paragraphs should not be indented with spaces or tabs.' },
  { type: 'paragraph',
    text: 'The implication of the "one or more consecutive lines of text" rule is\nthat Markdown supports "hard-wrapped" text paragraphs. This differs\nsignificantly from most other text-to-HTML formatters (including Movable\nType\'s "Convert Line Breaks" option) which translate every line break\ncharacter in a paragraph into a `<br />` tag.' },
  { type: 'paragraph',
    text: 'When you *do* want to insert a `<br />` break tag using Markdown, you\nend a line with two or more spaces, then type return.' },
  { type: 'paragraph',
    text: 'Yes, this takes a tad more effort to create a `<br />`, but a simplistic\n"every line break is a `<br />`" rule wouldn\'t work for Markdown.\nMarkdown\'s email-style [blockquoting][bq] and multi-paragraph [list items][l]\nwork best -- and look better -- when you format them with hard breaks.' },
  { type: 'html',
    pre: false,
    text: '<h3 id="header">Headers</h3>\n\n' },
  { type: 'paragraph',
    text: 'Markdown supports two styles of headers, [Setext] [1] and [atx] [2].' },
  { type: 'paragraph',
    text: 'Setext-style headers are "underlined" using equal signs (for first-level\nheaders) and dashes (for second-level headers). For example:' },
  { type: 'code',
    text: 'This is an H1\n=============\n\nThis is an H2\n-------------' },
  { type: 'paragraph',
    text: 'Any number of underlining `=`\'s or `-`\'s will work.' },
  { type: 'paragraph',
    text: 'Atx-style headers use 1-6 hash characters at the start of the line,\ncorresponding to header levels 1-6. For example:' },
  { type: 'code',
    text: '# This is an H1\n\n## This is an H2\n\n###### This is an H6' },
  { type: 'paragraph',
    text: 'Optionally, you may "close" atx-style headers. This is purely\ncosmetic -- you can use this if you think it looks better. The\nclosing hashes don\'t even need to match the number of hashes\nused to open the header. (The number of opening hashes\ndetermines the header level.) :' },
  { type: 'code',
    text: '# This is an H1 #\n\n## This is an H2 ##\n\n### This is an H3 ######' },
  { type: 'html',
    pre: false,
    text: '<h3 id="blockquote">Blockquotes</h3>\n\n' },
  { type: 'paragraph',
    text: 'Markdown uses email-style `>` characters for blockquoting. If you\'re\nfamiliar with quoting passages of text in an email message, then you\nknow how to create a blockquote in Markdown. It looks best if you hard\nwrap the text and put a `>` before every line:' },
  { type: 'code',
    text: '> This is a blockquote with two paragraphs. Lorem ipsum dolor sit amet,\n> consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus.\n> Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.\n> \n> Donec sit amet nisl. Aliquam semper ipsum sit amet velit. Suspendisse\n> id sem consectetuer libero luctus adipiscing.' },
  { type: 'paragraph',
    text: 'Markdown allows you to be lazy and only put the `>` before the first\nline of a hard-wrapped paragraph:' },
  { type: 'code',
    text: '> This is a blockquote with two paragraphs. Lorem ipsum dolor sit amet,\nconsectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus.\nVestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.\n\n> Donec sit amet nisl. Aliquam semper ipsum sit amet velit. Suspendisse\nid sem consectetuer libero luctus adipiscing.' },
  { type: 'paragraph',
    text: 'Blockquotes can be nested (i.e. a blockquote-in-a-blockquote) by\nadding additional levels of `>`:' },
  { type: 'code',
    text: '> This is the first level of quoting.\n>\n> > This is nested blockquote.\n>\n> Back to the first level.' },
  { type: 'paragraph',
    text: 'Blockquotes can contain other Markdown elements, including headers, lists,\nand code blocks:' },
  { type: 'blockquote_start' },
  { type: 'heading', depth: 2, text: 'This is a header.' },
  { type: 'list_start', ordered: true },
  { type: 'list_item_start' },
  { type: 'text', text: 'This is the first list item.' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: 'This is the second list item.' },
  { type: 'space' },
  { type: 'list_item_end' },
  { type: 'list_end' },
  { type: 'paragraph', text: 'Here\'s some example code:' },
  { type: 'code',
    text: 'return shell_exec("echo $input | $markdown_script");' },
  { type: 'blockquote_end' },
  { type: 'paragraph',
    text: 'Any decent text editor should make email-style quoting easy. For\nexample, with BBEdit, you can make a selection and choose Increase\nQuote Level from the Text menu.' },
  { type: 'html',
    pre: false,
    text: '<h3 id="list">Lists</h3>\n\n' },
  { type: 'paragraph',
    text: 'Markdown supports ordered (numbered) and unordered (bulleted) lists.' },
  { type: 'paragraph',
    text: 'Unordered lists use asterisks, pluses, and hyphens -- interchangably\n-- as list markers:' },
  { type: 'code', text: '*   Red\n*   Green\n*   Blue' },
  { type: 'paragraph', text: 'is equivalent to:' },
  { type: 'code', text: '+   Red\n+   Green\n+   Blue' },
  { type: 'paragraph', text: 'and:' },
  { type: 'code', text: '-   Red\n-   Green\n-   Blue' },
  { type: 'paragraph',
    text: 'Ordered lists use numbers followed by periods:' },
  { type: 'code', text: '1.  Bird\n2.  McHale\n3.  Parish' },
  { type: 'paragraph',
    text: 'It\'s important to note that the actual numbers you use to mark the\nlist have no effect on the HTML output Markdown produces. The HTML\nMarkdown produces from the above list is:' },
  { type: 'code',
    text: '<ol>\n<li>Bird</li>\n<li>McHale</li>\n<li>Parish</li>\n</ol>' },
  { type: 'paragraph',
    text: 'If you instead wrote the list in Markdown like this:' },
  { type: 'code', text: '1.  Bird\n1.  McHale\n1.  Parish' },
  { type: 'paragraph', text: 'or even:' },
  { type: 'code', text: '3. Bird\n1. McHale\n8. Parish' },
  { type: 'paragraph',
    text: 'you\'d get the exact same HTML output. The point is, if you want to,\nyou can use ordinal numbers in your ordered Markdown lists, so that\nthe numbers in your source match the numbers in your published HTML.\nBut if you want to be lazy, you don\'t have to.' },
  { type: 'paragraph',
    text: 'If you do use lazy list numbering, however, you should still start the\nlist with the number 1. At some point in the future, Markdown may support\nstarting ordered lists at an arbitrary number.' },
  { type: 'paragraph',
    text: 'List markers typically start at the left margin, but may be indented by\nup to three spaces. List markers must be followed by one or more spaces\nor a tab.' },
  { type: 'paragraph',
    text: 'To make lists look nice, you can wrap items with hanging indents:' },
  { type: 'code',
    text: '*   Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n    Aliquam hendrerit mi posuere lectus. Vestibulum enim wisi,\n    viverra nec, fringilla in, laoreet vitae, risus.\n*   Donec sit amet nisl. Aliquam semper ipsum sit amet velit.\n    Suspendisse id sem consectetuer libero luctus adipiscing.' },
  { type: 'paragraph',
    text: 'But if you want to be lazy, you don\'t have to:' },
  { type: 'code',
    text: '*   Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\nAliquam hendrerit mi posuere lectus. Vestibulum enim wisi,\nviverra nec, fringilla in, laoreet vitae, risus.\n*   Donec sit amet nisl. Aliquam semper ipsum sit amet velit.\nSuspendisse id sem consectetuer libero luctus adipiscing.' },
  { type: 'paragraph',
    text: 'If list items are separated by blank lines, Markdown will wrap the\nitems in `<p>` tags in the HTML output. For example, this input:' },
  { type: 'code', text: '*   Bird\n*   Magic' },
  { type: 'paragraph', text: 'will turn into:' },
  { type: 'code',
    text: '<ul>\n<li>Bird</li>\n<li>Magic</li>\n</ul>' },
  { type: 'paragraph', text: 'But this:' },
  { type: 'code', text: '*   Bird\n\n*   Magic' },
  { type: 'paragraph', text: 'will turn into:' },
  { type: 'code',
    text: '<ul>\n<li><p>Bird</p></li>\n<li><p>Magic</p></li>\n</ul>' },
  { type: 'paragraph',
    text: 'List items may consist of multiple paragraphs. Each subsequent\nparagraph in a list item must be indented by either 4 spaces\nor one tab:' },
  { type: 'code',
    text: '1.  This is a list item with two paragraphs. Lorem ipsum dolor\n    sit amet, consectetuer adipiscing elit. Aliquam hendrerit\n    mi posuere lectus.\n\n    Vestibulum enim wisi, viverra nec, fringilla in, laoreet\n    vitae, risus. Donec sit amet nisl. Aliquam semper ipsum\n    sit amet velit.\n\n2.  Suspendisse id sem consectetuer libero luctus adipiscing.' },
  { type: 'paragraph',
    text: 'It looks nice if you indent every line of the subsequent\nparagraphs, but here again, Markdown will allow you to be\nlazy:' },
  { type: 'code',
    text: '*   This is a list item with two paragraphs.\n\n    This is the second paragraph in the list item. You\'re\nonly required to indent the first line. Lorem ipsum dolor\nsit amet, consectetuer adipiscing elit.\n\n*   Another item in the same list.' },
  { type: 'paragraph',
    text: 'To put a blockquote within a list item, the blockquote\'s `>`\ndelimiters need to be indented:' },
  { type: 'code',
    text: '*   A list item with a blockquote:\n\n    > This is a blockquote\n    > inside a list item.' },
  { type: 'paragraph',
    text: 'To put a code block within a list item, the code block needs\nto be indented *twice* -- 8 spaces or two tabs:' },
  { type: 'code',
    text: '*   A list item with a code block:\n\n        <code goes here>' },
  { type: 'paragraph',
    text: 'It\'s worth noting that it\'s possible to trigger an ordered list by\naccident, by writing something like this:' },
  { type: 'code', text: '1986. What a great season.' },
  { type: 'paragraph',
    text: 'In other words, a *number-period-space* sequence at the beginning of a\nline. To avoid this, you can backslash-escape the period:' },
  { type: 'code', text: '1986\\. What a great season.' },
  { type: 'html',
    pre: false,
    text: '<h3 id="precode">Code Blocks</h3>\n\n' },
  { type: 'paragraph',
    text: 'Pre-formatted code blocks are used for writing about programming or\nmarkup source code. Rather than forming normal paragraphs, the lines\nof a code block are interpreted literally. Markdown wraps a code block\nin both `<pre>` and `<code>` tags.' },
  { type: 'paragraph',
    text: 'To produce a code block in Markdown, simply indent every line of the\nblock by at least 4 spaces or 1 tab. For example, given this input:' },
  { type: 'code',
    text: 'This is a normal paragraph:\n\n    This is a code block.' },
  { type: 'paragraph', text: 'Markdown will generate:' },
  { type: 'code',
    text: '<p>This is a normal paragraph:</p>\n\n<pre><code>This is a code block.\n</code></pre>' },
  { type: 'paragraph',
    text: 'One level of indentation -- 4 spaces or 1 tab -- is removed from each\nline of the code block. For example, this:' },
  { type: 'code',
    text: 'Here is an example of AppleScript:\n\n    tell application "Foo"\n        beep\n    end tell' },
  { type: 'paragraph', text: 'will turn into:' },
  { type: 'code',
    text: '<p>Here is an example of AppleScript:</p>\n\n<pre><code>tell application "Foo"\n    beep\nend tell\n</code></pre>' },
  { type: 'paragraph',
    text: 'A code block continues until it reaches a line that is not indented\n(or the end of the article).' },
  { type: 'paragraph',
    text: 'Within a code block, ampersands (`&`) and angle brackets (`<` and `>`)\nare automatically converted into HTML entities. This makes it very\neasy to include example HTML source code using Markdown -- just paste\nit and indent it, and Markdown will handle the hassle of encoding the\nampersands and angle brackets. For example, this:' },
  { type: 'code',
    text: '    <div class="footer">\n        &copy; 2004 Foo Corporation\n    </div>' },
  { type: 'paragraph', text: 'will turn into:' },
  { type: 'code',
    text: '<pre><code>&lt;div class="footer"&gt;\n    &amp;copy; 2004 Foo Corporation\n&lt;/div&gt;\n</code></pre>' },
  { type: 'paragraph',
    text: 'Regular Markdown syntax is not processed within code blocks. E.g.,\nasterisks are just literal asterisks within a code block. This means\nit\'s also easy to use Markdown to write about Markdown\'s own syntax.' },
  { type: 'html',
    pre: false,
    text: '<h3 id="hr">Horizontal Rules</h3>\n\n' },
  { type: 'paragraph',
    text: 'You can produce a horizontal rule tag (`<hr />`) by placing three or\nmore hyphens, asterisks, or underscores on a line by themselves. If you\nwish, you may use spaces between the hyphens or asterisks. Each of the\nfollowing lines will produce a horizontal rule:' },
  { type: 'code',
    text: '* * *\n\n***\n\n*****\n\n- - -\n\n---------------------------------------' },
  { type: 'hr' },
  { type: 'html',
    pre: false,
    text: '<h2 id="span">Span Elements</h2>\n\n' },
  { type: 'html',
    pre: false,
    text: '<h3 id="link">Links</h3>\n\n' },
  { type: 'paragraph',
    text: 'Markdown supports two style of links: *inline* and *reference*.' },
  { type: 'paragraph',
    text: 'In both styles, the link text is delimited by [square brackets].' },
  { type: 'paragraph',
    text: 'To create an inline link, use a set of regular parentheses immediately\nafter the link text\'s closing square bracket. Inside the parentheses,\nput the URL where you want the link to point, along with an *optional*\ntitle for the link, surrounded in quotes. For example:' },
  { type: 'code',
    text: 'This is [an example](http://example.com/ "Title") inline link.\n\n[This link](http://example.net/) has no title attribute.' },
  { type: 'paragraph', text: 'Will produce:' },
  { type: 'code',
    text: '<p>This is <a href="http://example.com/" title="Title">\nan example</a> inline link.</p>\n\n<p><a href="http://example.net/">This link</a> has no\ntitle attribute.</p>' },
  { type: 'paragraph',
    text: 'If you\'re referring to a local resource on the same server, you can\nuse relative paths:' },
  { type: 'code',
    text: 'See my [About](/about/) page for details.   ' },
  { type: 'paragraph',
    text: 'Reference-style links use a second set of square brackets, inside\nwhich you place a label of your choosing to identify the link:' },
  { type: 'code',
    text: 'This is [an example][id] reference-style link.' },
  { type: 'paragraph',
    text: 'You can optionally use a space to separate the sets of brackets:' },
  { type: 'code',
    text: 'This is [an example] [id] reference-style link.' },
  { type: 'paragraph',
    text: 'Then, anywhere in the document, you define your link label like this,\non a line by itself:' },
  { type: 'code',
    text: '[id]: http://example.com/  "Optional Title Here"' },
  { type: 'paragraph', text: 'That is:' },
  { type: 'list_start', ordered: false },
  { type: 'list_item_start' },
  { type: 'text',
    text: 'Square brackets containing the link identifier (optionally' },
  { type: 'text',
    text: 'indented from the left margin using up to three spaces);' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: 'followed by a colon;' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text',
    text: 'followed by one or more spaces (or tabs);' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: 'followed by the URL for the link;' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text',
    text: 'optionally followed by a title attribute for the link, enclosed' },
  { type: 'text',
    text: 'in double or single quotes, or enclosed in parentheses.' },
  { type: 'space' },
  { type: 'list_item_end' },
  { type: 'list_end' },
  { type: 'paragraph',
    text: 'The following three link definitions are equivalent:' },
  { type: 'paragraph',
    text: '  [foo]: http://example.com/  \'Optional Title Here\'' },
  { type: 'paragraph',
    text: '**Note:** There is a known bug in Markdown.pl 1.0.1 which prevents\nsingle quotes from being used to delimit link titles.' },
  { type: 'paragraph',
    text: 'The link URL may, optionally, be surrounded by angle brackets:' },
  { type: 'code',
    text: '[id]: <http://example.com/>  "Optional Title Here"' },
  { type: 'paragraph',
    text: 'You can put the title attribute on the next line and use extra spaces\nor tabs for padding, which tends to look better with longer URLs:' },
  { type: 'code',
    text: '[id]: http://example.com/longish/path/to/resource/here\n    "Optional Title Here"' },
  { type: 'paragraph',
    text: 'Link definitions are only used for creating links during Markdown\nprocessing, and are stripped from your document in the HTML output.' },
  { type: 'paragraph',
    text: 'Link definition names may consist of letters, numbers, spaces, and\npunctuation -- but they are *not* case sensitive. E.g. these two\nlinks:' },
  { type: 'paragraph',
    text: '  [link text][a]\n  [link text][A]' },
  { type: 'paragraph', text: 'are equivalent.' },
  { type: 'paragraph',
    text: 'The *implicit link name* shortcut allows you to omit the name of the\nlink, in which case the link text itself is used as the name.\nJust use an empty set of square brackets -- e.g., to link the word\n"Google" to the google.com web site, you could simply write:' },
  { type: 'paragraph', text: '  [Google][]' },
  { type: 'paragraph', text: 'And then define the link:' },
  { type: 'paragraph',
    text: 'Because link names may contain spaces, this shortcut even works for\nmultiple words in the link text:' },
  { type: 'paragraph',
    text: '  Visit [Daring Fireball][] for more information.' },
  { type: 'paragraph', text: 'And then define the link:' },
  { type: 'paragraph',
    text: 'Link definitions can be placed anywhere in your Markdown document. I\ntend to put them immediately after each paragraph in which they\'re\nused, but if you want, you can put them all at the end of your\ndocument, sort of like footnotes.' },
  { type: 'paragraph',
    text: 'Here\'s an example of reference links in action:' },
  { type: 'code',
    text: 'I get 10 times more traffic from [Google] [1] than from\n[Yahoo] [2] or [MSN] [3].\n\n  [1]: http://google.com/        "Google"\n  [2]: http://search.yahoo.com/  "Yahoo Search"\n  [3]: http://search.msn.com/    "MSN Search"' },
  { type: 'paragraph',
    text: 'Using the implicit link name shortcut, you could instead write:' },
  { type: 'code',
    text: 'I get 10 times more traffic from [Google][] than from\n[Yahoo][] or [MSN][].\n\n  [google]: http://google.com/        "Google"\n  [yahoo]:  http://search.yahoo.com/  "Yahoo Search"\n  [msn]:    http://search.msn.com/    "MSN Search"' },
  { type: 'paragraph',
    text: 'Both of the above examples will produce the following HTML output:' },
  { type: 'code',
    text: '<p>I get 10 times more traffic from <a href="http://google.com/"\ntitle="Google">Google</a> than from\n<a href="http://search.yahoo.com/" title="Yahoo Search">Yahoo</a>\nor <a href="http://search.msn.com/" title="MSN Search">MSN</a>.</p>' },
  { type: 'paragraph',
    text: 'For comparison, here is the same paragraph written using\nMarkdown\'s inline link style:' },
  { type: 'code',
    text: 'I get 10 times more traffic from [Google](http://google.com/ "Google")\nthan from [Yahoo](http://search.yahoo.com/ "Yahoo Search") or\n[MSN](http://search.msn.com/ "MSN Search").' },
  { type: 'paragraph',
    text: 'The point of reference-style links is not that they\'re easier to\nwrite. The point is that with reference-style links, your document\nsource is vastly more readable. Compare the above examples: using\nreference-style links, the paragraph itself is only 81 characters\nlong; with inline-style links, it\'s 176 characters; and as raw HTML,\nit\'s 234 characters. In the raw HTML, there\'s more markup than there\nis text.' },
  { type: 'paragraph',
    text: 'With Markdown\'s reference-style links, a source document much more\nclosely resembles the final output, as rendered in a browser. By\nallowing you to move the markup-related metadata out of the paragraph,\nyou can add links without interrupting the narrative flow of your\nprose.' },
  { type: 'html',
    pre: false,
    text: '<h3 id="em">Emphasis</h3>\n\n' },
  { type: 'paragraph',
    text: 'Markdown treats asterisks (`*`) and underscores (`_`) as indicators of\nemphasis. Text wrapped with one `*` or `_` will be wrapped with an\nHTML `<em>` tag; double `*`\'s or `_`\'s will be wrapped with an HTML\n`<strong>` tag. E.g., this input:' },
  { type: 'code',
    text: '*single asterisks*\n\n_single underscores_\n\n**double asterisks**\n\n__double underscores__' },
  { type: 'paragraph', text: 'will produce:' },
  { type: 'code',
    text: '<em>single asterisks</em>\n\n<em>single underscores</em>\n\n<strong>double asterisks</strong>\n\n<strong>double underscores</strong>' },
  { type: 'paragraph',
    text: 'You can use whichever style you prefer; the lone restriction is that\nthe same character must be used to open and close an emphasis span.' },
  { type: 'paragraph',
    text: 'Emphasis can be used in the middle of a word:' },
  { type: 'code', text: 'un*frigging*believable' },
  { type: 'paragraph',
    text: 'But if you surround an `*` or `_` with spaces, it\'ll be treated as a\nliteral asterisk or underscore.' },
  { type: 'paragraph',
    text: 'To produce a literal asterisk or underscore at a position where it\nwould otherwise be used as an emphasis delimiter, you can backslash\nescape it:' },
  { type: 'code',
    text: '\\*this text is surrounded by literal asterisks\\*' },
  { type: 'html', pre: false, text: '<h3 id="code">Code</h3>\n\n' },
  { type: 'paragraph',
    text: 'To indicate a span of code, wrap it with backtick quotes (`` ` ``).\nUnlike a pre-formatted code block, a code span indicates code within a\nnormal paragraph. For example:' },
  { type: 'code', text: 'Use the `printf()` function.' },
  { type: 'paragraph', text: 'will produce:' },
  { type: 'code',
    text: '<p>Use the <code>printf()</code> function.</p>' },
  { type: 'paragraph',
    text: 'To include a literal backtick character within a code span, you can use\nmultiple backticks as the opening and closing delimiters:' },
  { type: 'code',
    text: '``There is a literal backtick (`) here.``' },
  { type: 'paragraph', text: 'which will produce this:' },
  { type: 'code',
    text: '<p><code>There is a literal backtick (`) here.</code></p>' },
  { type: 'paragraph',
    text: 'The backtick delimiters surrounding a code span may include spaces --\none after the opening, one before the closing. This allows you to place\nliteral backtick characters at the beginning or end of a code span:' },
  { type: 'paragraph',
    text: '  A single backtick in a code span: `` ` ``' },
  { type: 'paragraph',
    text: '  A backtick-delimited string in a code span: `` `foo` ``' },
  { type: 'paragraph', text: 'will produce:' },
  { type: 'html',
    pre: false,
    text: '  <p>A single backtick in a code span: <code>`</code></p>\n\n' },
  { type: 'html',
    pre: false,
    text: '  <p>A backtick-delimited string in a code span: <code>`foo`</code></p>\n\n' },
  { type: 'paragraph',
    text: 'With a code span, ampersands and angle brackets are encoded as HTML\nentities automatically, which makes it easy to include example HTML\ntags. Markdown will turn this:' },
  { type: 'code', text: 'Please don\'t use any `<blink>` tags.' },
  { type: 'paragraph', text: 'into:' },
  { type: 'code',
    text: '<p>Please don\'t use any <code>&lt;blink&gt;</code> tags.</p>' },
  { type: 'paragraph', text: 'You can write this:' },
  { type: 'code',
    text: '`&#8212;` is the decimal-encoded equivalent of `&mdash;`.' },
  { type: 'paragraph', text: 'to produce:' },
  { type: 'code',
    text: '<p><code>&amp;#8212;</code> is the decimal-encoded\nequivalent of <code>&amp;mdash;</code>.</p>' },
  { type: 'html',
    pre: false,
    text: '<h3 id="img">Images</h3>\n\n' },
  { type: 'paragraph',
    text: 'Admittedly, it\'s fairly difficult to devise a "natural" syntax for\nplacing images into a plain text document format.' },
  { type: 'paragraph',
    text: 'Markdown uses an image syntax that is intended to resemble the syntax\nfor links, allowing for two styles: *inline* and *reference*.' },
  { type: 'paragraph',
    text: 'Inline image syntax looks like this:' },
  { type: 'code',
    text: '![Alt text](/path/to/img.jpg)\n\n![Alt text](/path/to/img.jpg "Optional title")' },
  { type: 'paragraph', text: 'That is:' },
  { type: 'list_start', ordered: false },
  { type: 'list_item_start' },
  { type: 'text', text: 'An exclamation mark: `!`;' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text',
    text: 'followed by a set of square brackets, containing the `alt`' },
  { type: 'text', text: 'attribute text for the image;' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text',
    text: 'followed by a set of parentheses, containing the URL or path to' },
  { type: 'text',
    text: 'the image, and an optional `title` attribute enclosed in double' },
  { type: 'text', text: 'or single quotes.' },
  { type: 'space' },
  { type: 'list_item_end' },
  { type: 'list_end' },
  { type: 'paragraph',
    text: 'Reference-style image syntax looks like this:' },
  { type: 'code', text: '![Alt text][id]' },
  { type: 'paragraph',
    text: 'Where "id" is the name of a defined image reference. Image references\nare defined using syntax identical to link references:' },
  { type: 'code',
    text: '[id]: url/to/image  "Optional title attribute"' },
  { type: 'paragraph',
    text: 'As of this writing, Markdown has no syntax for specifying the\ndimensions of an image; if this is important to you, you can simply\nuse regular HTML `<img>` tags.' },
  { type: 'hr' },
  { type: 'html',
    pre: false,
    text: '<h2 id="misc">Miscellaneous</h2>\n\n' },
  { type: 'html',
    pre: false,
    text: '<h3 id="autolink">Automatic Links</h3>\n\n' },
  { type: 'paragraph',
    text: 'Markdown supports a shortcut style for creating "automatic" links for URLs and email addresses: simply surround the URL or email address with angle brackets. What this means is that if you want to show the actual text of a URL or email address, and also have it be a clickable link, you can do this:' },
  { type: 'code', text: '<http://example.com/>' },
  { type: 'paragraph', text: 'Markdown will turn this into:' },
  { type: 'code',
    text: '<a href="http://example.com/">http://example.com/</a>' },
  { type: 'paragraph',
    text: 'Automatic links for email addresses work similarly, except that\nMarkdown will also perform a bit of randomized decimal and hex\nentity-encoding to help obscure your address from address-harvesting\nspambots. For example, Markdown will turn this:' },
  { type: 'code', text: '<address@example.com>' },
  { type: 'paragraph', text: 'into something like this:' },
  { type: 'code',
    text: '<a href="&#x6D;&#x61;i&#x6C;&#x74;&#x6F;:&#x61;&#x64;&#x64;&#x72;&#x65;\n&#115;&#115;&#64;&#101;&#120;&#x61;&#109;&#x70;&#x6C;e&#x2E;&#99;&#111;\n&#109;">&#x61;&#x64;&#x64;&#x72;&#x65;&#115;&#115;&#64;&#101;&#120;&#x61;\n&#109;&#x70;&#x6C;e&#x2E;&#99;&#111;&#109;</a>' },
  { type: 'paragraph',
    text: 'which will render in a browser as a clickable link to "address@example.com".' },
  { type: 'paragraph',
    text: '(This sort of entity-encoding trick will indeed fool many, if not\nmost, address-harvesting bots, but it definitely won\'t fool all of\nthem. It\'s better than nothing, but an address published in this way\nwill probably eventually start receiving spam.)' },
  { type: 'html',
    pre: false,
    text: '<h3 id="backslash">Backslash Escapes</h3>\n\n' },
  { type: 'paragraph',
    text: 'Markdown allows you to use backslash escapes to generate literal\ncharacters which would otherwise have special meaning in Markdown\'s\nformatting syntax. For example, if you wanted to surround a word\nwith literal asterisks (instead of an HTML `<em>` tag), you can use\nbackslashes before the asterisks, like this:' },
  { type: 'code', text: '\\*literal asterisks\\*' },
  { type: 'paragraph',
    text: 'Markdown provides backslash escapes for the following characters:' },
  { type: 'code',
    text: '\\   backslash\n`   backtick\n*   asterisk\n_   underscore\n{}  curly braces\n[]  square brackets\n()  parentheses\n#   hash mark' },
  { type: 'list_start', ordered: false },
  { type: 'list_item_start' },
  { type: 'text', text: 'plus sign' },
  { type: 'list_item_end' },
  { type: 'list_item_start' },
  { type: 'text', text: 'minus sign (hyphen)' },
  { type: 'text', text: '.   dot' },
  { type: 'text', text: '!   exclamation mark' },
  { type: 'space' },
  { type: 'list_item_end' },
  { type: 'list_end' },
  links: { '1': 
     { href: 'http://docutils.sourceforge.net/mirror/setext.html',
       title: undefined },
    '2': { href: 'http://www.aaronsw.com/2002/atx/', title: undefined },
    '3': { href: 'http://textism.com/tools/textile/', title: undefined },
    '4': 
     { href: 'http://docutils.sourceforge.net/rst.html',
       title: undefined },
    '5': 
     { href: 'http://www.triptico.com/software/grutatxt.html',
       title: undefined },
    '6': { href: 'http://ettext.taint.org/doc/', title: undefined },
    src: { href: '/projects/markdown/syntax.text', title: undefined },
    bq: { href: '#blockquote', title: undefined },
    l: { href: '#list', title: undefined },
    foo: { href: 'http://example.com/', title: 'Optional Title Here' },
    google: { href: 'http://google.com/', title: undefined },
    'daring fireball': { href: 'http://daringfireball.net/', title: undefined } } ]
